In [1]:
import glob
from astropy.io import fits
import numpy as np
import matplotlib.pyplot as plt

data_dir = "/Users/hunterholland/Documents/Research/Laidlaw/Data"

#### Denoting Sample Files

In [15]:
spitzer_sample = None
chandra_sample = f"{data_dir}/L1521E/Chandra/primary/acisf07419N002_evt2.fits"
xmm_sample = f"{data_dir}/L1251B&E/XMM/PPS/P0201540101PNS003EXPMAP8000.FTZ"
rosat_sample = None
swift_sample = None

#### Listing Instrument Event Files

In [14]:
# Spitzer


# Chandra
evt2 = glob.glob(f"{data_dir}/**/Chandra/**/*evt2.fits", recursive=True)

# XMM
mos_1 = glob.glob(f"{data_dir}/**/XMM/PPS/*M1*EXPMAP8*.FTZ", recursive=True)
mos_2 = glob.glob(f"{data_dir}/**/XMM/PPS/*M2*EXPMAP8*.FTZ", recursive=True)
pn = glob.glob(f"{data_dir}/**/XMM/PPS/*PN*EXPMAP8*.FTZ", recursive=True)

# Rosat


# Swift


['/Users/hunterholland/Documents/Research/Laidlaw/Data/L1251B&E/XMM/PPS/P0201540101PNS003EXPMAP8000.FTZ', '/Users/hunterholland/Documents/Research/Laidlaw/Data/B335/XMM/PPS/P0089940901PNS003EXPMAP8000.FTZ', '/Users/hunterholland/Documents/Research/Laidlaw/Data/L1262/XMM/PPS/P0650910301PNS003EXPMAP8000.FTZ', '/Users/hunterholland/Documents/Research/Laidlaw/Data/B59/XMM/PPS/P0206610101PNS003EXPMAP8000.FTZ', '/Users/hunterholland/Documents/Research/Laidlaw/Data/L1448/XMM/PPS/P0089940201PNS003EXPMAP8000.FTZ']


#### Making Energy Histograms (Chandra)

In [4]:
from chandra_functions import make_hist

obj_name = "L1521E"
filepath = chandra_sample
min_e = 6000
max_e = 10000
nbins = 75

make_hist(obj_name, filepath, min_e, max_e, nbins)

# Bulk Histogram Output (unfinished)
# for file in evt2:
#     make_hist(file, min_e, min_e, i=i)
#     i += 1

#### Making Energy Histograms (XMM-Newton)

In [21]:
# Energy Bands:
# 1: 0.2-0.5 keV; 2: 0.5-2 keV; 3: 2-4.5 keV; 4: 4.5-7.5 keV; 5: 7.5-12 keV; 8: 0.2-12 keV
obj_name = "L1251B&E"
filepath = xmm_sample
min_e = 6000
max_e = 10000
nbins = 75

hdu_list = fits.open(filepath, memmap=True)
hdu_list.info()
evt_data = hdu_list[0].data
print(evt_data)
# energy = evt_data["energy"]
# min_thresh = evt_data["energy"] >= min_e
# max_thresh = evt_data["energy"] < max_e
# e_band = energy[min_thresh & max_thresh]

Filename: /Users/hunterholland/Documents/Research/Laidlaw/Data/L1251B&E/XMM/PPS/P0201540101PNS003EXPMAP8000.FTZ
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     447   (648, 648)   float32   
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
